# Generated by Django 3.0.6 on 2021-02-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='text',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='owner',
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='day',
            field=models.TextField(blank=True, default='', max_length=80),
        ),
    ]
