# Generated by Django 3.0.6 on 2021-02-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tasks_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='owner',
        ),
    ]
