# Generated by Django 3.0.6 on 2021-04-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_tasks_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='day',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='reminder',
        ),
    ]
