# Generated by Django 3.0.6 on 2021-04-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210402_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='day',
            field=models.TextField(blank=True, default='', max_length=80),
        ),
    ]
